
const Sobre = () => {
    return(
        <div>
            <h1>Sobre</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quod similique, maiores aspernatur, quos impedit voluptatum culpa voluptatibus, neque incidunt nam? Harum maiores quae aut velit ex maxime. Adipisci incidunt asperiores illum doloremque repudiandae reprehenderit non ea perferendis atque ullam sequi eveniet et deleniti quis similique, excepturi porro! Esse, reiciendis, maiores, dolorem officia libero repellat corporis reprehenderit ullam non odit velit omnis dolores maxime temporibus rerum! Delectus laborum rem cupiditate totam iste dolor provident, et, ipsam assumenda, error laboriosam debitis modi corrupti vel amet eligendi est sequi perspiciatis? Esse amet eum laudantium labore suscipit rem cum aliquid nemo? Quasi sit nobis tempora nulla neque quaerat fugiat odio! Modi exercitationem ratione harum veniam molestias sequi sint accusamus labore quis perspiciatis! Totam cumque provident, inventore molestias sunt dicta. Quam fugiat ab incidunt cupiditate perspiciatis magni assumenda! Ipsam, vitae voluptas vel enim blanditiis eligendi voluptatem ipsa culpa voluptatibus animi quisquam a minima repellat odio accusamus sapiente officia! Ex delectus aspernatur commodi, modi sint accusamus, dignissimos unde, quo dolores neque odio. Autem, iure ullam vel inventore eaque nisi quisquam doloribus, magni quia consectetur earum pariatur. Blanditiis pariatur placeat sed mollitia tenetur, voluptas molestias necessitatibus magnam doloremque voluptates labore aspernatur cupiditate praesentium nulla deleniti autem animi ex est incidunt aperiam. Quisquam praesentium explicabo voluptas dolorem vero officiis, totam consectetur in, obcaecati est, voluptates a! Quas facere nostrum quo recusandae sed, quos inventore natus id fugiat consequatur sit. Quia inventore quo libero minus rerum architecto facere iusto ea quidem quasi, sit laboriosam reprehenderit perferendis, ab iste dolore quis ratione. In, vero nemo hic neque totam nostrum harum tempora architecto earum maiores maxime consequatur quidem placeat debitis ullam eum nam. Voluptatibus ducimus dolorum ullam laudantium eligendi exercitationem, iste laborum facere! Ipsum qui exercitationem, neque itaque perferendis quidem commodi, nulla nisi quia modi illum ipsa sequi, veniam sed.</p>
        </div>
    )
}

export default Sobre;